// Generated by Haxe 4.3.7
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var fsprobe_FsProbe = function() { };
fsprobe_FsProbe.missingRoot = function() {
	return "out/fs-missing/probe/definitely-missing";
};
fsprobe_FsProbe.say = function(label,text) {
	console.log(label + "|" + text);
};
fsprobe_FsProbe.messageOf = function(error) {
	if(error == null) {
		return "<not-caught>";
	} else {
		var bound = error;
		return bound.get_message();
	}
};
fsprobe_FsProbe.run = function() {
	var missing = fsprobe_FsProbe.missingRoot() + "/no-such-file.txt";
	fsprobe_FsProbe.say("m0","probe-start");
	var dir = std.Fs.isDirectory(missing);
	fsprobe_FsProbe.say("m1","isDirectory-returned|" + (dir == null ? "null" : "" + dir));
	var caught = false;
	var name = "<not-caught>";
	var message = "<not-caught>";
	try {
		var text = std.Fs.readText(missing);
		fsprobe_FsProbe.say("m2","readText-returned|" + text);
	} catch( _g ) {
		var _g1 = haxe_Exception.caught(_g);
		if(((_g1) instanceof fsprobe_FsProbeFault)) {
			var error = _g1;
			caught = true;
			name = "haxe.Exception";
			message = fsprobe_FsProbe.messageOf(error);
		} else {
			throw _g;
		}
	}
	fsprobe_FsProbe.say("m3","readText-catch-ran|" + (caught == null ? "null" : "" + caught));
	fsprobe_FsProbe.say("m4","caught-declared-class|" + name);
	fsprobe_FsProbe.say("m5","caught-message|" + message);
	fsprobe_FsProbe.say("m6","uncaught-region-start");
	var escaped = std.Fs.readText(missing);
	fsprobe_FsProbe.say("m7","uncaught-region-returned|" + escaped);
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_message: function() {
		return this.message;
	}
});
var fsprobe_FsProbeFault = function(message) {
	haxe_Exception.call(this,message);
};
fsprobe_FsProbeFault.__super__ = haxe_Exception;
fsprobe_FsProbeFault.prototype = $extend(haxe_Exception.prototype,{
});
var fsprobe_ProbeMain = function() { };
fsprobe_ProbeMain.main = function() {
	fsprobe_FsProbe.run();
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
fsprobe_ProbeMain.main();
})({});
