package tscompiler;

#if (macro || reflaxe_runtime)
import haxe.macro.Type;
import reflaxe.BaseCompiler.BaseCompilerFileOutputType;
import reflaxe.PluginCompiler;
import reflaxe.ReflectCompiler;
import reflaxe.data.ClassFuncData;
import reflaxe.data.ClassVarData;
import reflaxe.data.EnumOptionData;

/**
	reflaxe plugin producing the TypeScript lane of the translatable
	subset (docs/specs/targets/07-reflaxe-typescript-target.md).

	Output layout is one file per Haxe module under `boring/`, plus a
	`runtime.ts` sibling, all written through the framework's output
	manager so `-D ts-output=<dir>` controls placement.
**/
class Compiler extends PluginCompiler<Compiler> {
	/** Module-base name to declaration parts, in arrival order. */
	final parts: Map<String, Array<String>> = [];

	/** Module-base name to emission context (imports per file). */
	final contexts: Map<String, TsDecl> = [];

	var current: Null<TsDecl> = null;

	public static function use() {
		ReflectCompiler.AddCompiler(new Compiler(), {
			fileOutputType: BaseCompilerFileOutputType.Manual,
			fileOutputExtension: ".ts",
			outputDirDefineName: "ts-output",
			unwrapTypedefs: false,
			normalizeEIE: false,
			preventRepeatVars: false,
			ignoreExterns: true,
		});
	}

	public function new() {
		super();
	}

	// ------------------------------------------------------------------
	// Declarations
	// ------------------------------------------------------------------

	public function compileClassImpl(classType: ClassType, varFields: Array<ClassVarData>, funcFields: Array<ClassFuncData>): Null<String> {
		if(!isBoringPack(classType.pack)) {
			return null;
		}
		final decl = contextFor(classType.module);
		final result = decl.classDecl(classType, varFields, funcFields);
		parts.get(moduleBase(classType.module)).push(result);
		return result;
	}

	public function compileEnumImpl(enumType: EnumType, options: Array<EnumOptionData>): Null<String> {
		if(!isBoringPack(enumType.pack)) {
			return null;
		}
		final decl = contextFor(enumType.module);
		final result = decl.enumDecl(enumType, options);
		parts.get(moduleBase(enumType.module)).push(result);
		return result;
	}

	public override function compileTypedef(def: DefType): Null<String> {
		if(!isBoringPack(def.pack)) {
			return null;
		}
		switch(def.type) {
			case TAnonymous(_):
			case _:
				return null;
		}
		final decl = contextFor(def.module);
		final result = decl.typedefDecl(def);
		parts.get(moduleBase(def.module)).push(result);
		return result;
	}

	/**
		Entry point for expressions the framework itself needs lowered
		(field initializers and the like). Everything flows through the
		same typed-AST translator as class bodies.
	**/
	public function compileExpressionImpl(e: TypedExpr, topLevel: Bool): Null<String> {
		final decl = current != null ? current : new TsDecl("eval");
		return topLevel ? decl.topLevelStatements(e) : decl.rawExpression(e);
	}

	// ------------------------------------------------------------------
	// Output
	// ------------------------------------------------------------------

	public override function generateFilesManually() {
		final modules = [];
		for(module in parts.keys()) modules.push(module);
		modules.sort(Reflect.compare);
		for(module in modules) {
			final decl = contexts.get(module);
			final imports = decl.renderImports();
			final body = parts.get(module).join("\n\n");
			final content = '// Generated by the reflaxe TypeScript target. Do not edit.\n\n'
				+ imports
				+ (imports.length > 0 ? "\n" : "")
				+ body
				+ "\n";
			output.saveFile('boring/$module.ts', content);
		}
		output.saveFile("runtime.ts", StringTools.trim(TsRuntime.SOURCE) + "\n");
	}

	// ------------------------------------------------------------------
	// Internals
	// ------------------------------------------------------------------

	function contextFor(module: String): TsDecl {
		final base = moduleBase(module);
		current = contexts.exists(base) ? contexts.get(base) : null;
		if(current == null) {
			current = new TsDecl(base);
			contexts.set(base, current);
			parts.set(base, []);
		}
		return current;
	}

	function moduleBase(module: String): String {
		final segments = module.split(".");
		return segments[segments.length - 1];
	}

	function isBoringPack(pack: Array<String>): Bool {
		return pack.length == 1 && pack[0] == "boring";
	}
}
#end
