import type { TSESTree } from "@typescript-eslint/utils";
import type { BoringRule, VisitNode } from "../rule-types.ts";

type InlineTypeNode =
  | TSESTree.TSTypeLiteral
  | TSESTree.TSFunctionType
  | TSESTree.TSMappedType
  | TSESTree.TSTupleType;

type InlineTypesVisitor = {
  TSMappedType: VisitNode<TSESTree.TSMappedType>;
  TSFunctionType: VisitNode<TSESTree.TSFunctionType>;
  TSTupleType: VisitNode<TSESTree.TSTupleType>;
  TSTypeLiteral: VisitNode<TSESTree.TSTypeLiteral>;
};

const KIND_NAMES: Readonly<Record<string, string>> = {
  TSMappedType: "mapped type",
  TSFunctionType: "function type",
  TSTupleType: "tuple type",
  TSTypeLiteral: "object type",
};

function isDirectAliasRhs(node: InlineTypeNode): boolean {
  // typescript-estree normalizes parenthesized types away, so the alias
  // right-hand side is always the direct parent of the inline type node.
  return node.parent !== undefined && node.parent.type === "TSTypeAliasDeclaration";
}

/**
 * Bans inline object, mapped, and tuple types outside of a named type alias.
 * Haxe-generated TypeScript keeps native inline function signatures because
 * feature 29 rules those signatures as the target spelling; authored
 * TypeScript still binds function types to names at their use sites.
 */
export const noInlineTypes: BoringRule<InlineTypesVisitor, "inlineType"> = {
  meta: {
    type: "problem",
    docs: {
      description:
        "Bans inline object, mapped, and tuple types outside of a named type alias.",
    },
    schema: [],
    messages: {
      inlineType:
        "Inline {{kind}} is banned here. Bind it to a name with `type` or `interface` and reference the name at this position.",
    },
  },
  create(context) {
    const inGeneratedTarget = context.sourceCode.text.startsWith(
      "// Generated by the reflaxe TypeScript target. Do not edit.",
    );

    function check(node: InlineTypeNode): void {
      if (isDirectAliasRhs(node)) return;
      if (node.type === "TSFunctionType" && inGeneratedTarget) return;
      context.report({
        node,
        messageId: "inlineType",
        data: { kind: KIND_NAMES[node.type] ?? "type" },
      });
    }

    return {
      TSMappedType: check,
      TSFunctionType: check,
      TSTupleType: check,
      TSTypeLiteral: check,
    };
  },
};
