// Generated by the reflaxe Swift target. Do not edit.

public class UStringException: BoringException {
    public let fault: UStringFault

    public init(_ fault: UStringFault) {
        self.fault = fault
        super.init(message: UStringException.describe(fault))
    }

    public static func describe(_ fault: UStringFault) -> String {
        switch fault {
            case .invalidCodePoint(let code):
                return "invalid code point: \(code)"
            case .unpairedSurrogate(let unit):
                return "unpaired surrogate: \(unit)"
        }
    }
}
