package dartcompiler;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Type;

/**
	Generates the two fixed entries of the generated test tree
	(features/19): the `main` runner that registers every @:test
	function in id order, and the per-type deep equality, canonical
	formatting, and assertion functions the type-guided Test.equals
	calls resolve to. The canonical text follows the format the
	TypeScript host defined: comma-space separators, `{field: value}`
	records, `Kind(p1, p2)` variants under their original construct
	names.
**/
class DartTestHelper {
	/**
		The runner entry: one main function registering every @:test
		function in id order. The test modules lower to top-level
		functions of their own libraries, so each call reaches through
		the module's import prefix.
	**/
	public static function testMainSource(entries: Array<{id: String, runnerName: String, module: String, fn: String}>): String {
		final sorted = entries.copy();
		sorted.sort((a, b) -> Reflect.compare(a.id, b.id));
		final modules: Array<String> = [];
		for(e in sorted) {
			if(modules.indexOf(e.module) < 0) {
				modules.push(e.module);
			}
		}
		final lines: Array<String> = [
			"// Generated by the reflaxe Dart target. Do not edit.",
			"",
			"import 'dart:io';",
			"",
			"import 'test_host.dart' as test_host;"
		];
		for(m in modules) {
			// The test module's own pack is `tests`, so its library path
			// already carries the subdirectory relative to the runner.
			lines.push("import '" + DartImports.libraryPathOf(m) + "' as " + DartImports.importPrefixOf(m) + ";");
		}
		lines.push("");
		lines.push("void main() {");
		lines.push("  var failures = 0;");
		for(e in sorted) {
			lines.push("  if (test_host.run('" + escapeDartString(e.id) + "', '" + escapeDartString(e.runnerName) + "', () => " + DartImports.importPrefixOf(e.module) + "." + e.fn + "())) {");
			lines.push("    failures++;");
			lines.push("  }");
		}
		lines.push("  exitCode = failures > 0 ? 1 : 0;");
		lines.push("}");
		return lines.join("\n") + "\n";
	}

	/**
		The helper library: one assertion, one deep equality, and one
		formatter per registered composite type. Equality is generated
		per type because the native operator on lists compares
		references; records and variants compare through their own
		generated operators.
	**/
	public static function testHelperSource(imports: DartImports, types: DartType): String {
		final entries = DartTestTypes.registered.copy();
		entries.sort((a, b) -> Reflect.compare(a.tag, b.tag));
		// Register the defining module of every named type the generated
		// bodies reach, including ones nested inside records and variant
		// payloads that never surface in a signature.
		for(entry in entries) {
			registerTypeModules(imports, entry.type, new Map<String, Bool>());
		}
		final chunks: Array<String> = [
			"// Generated by the reflaxe Dart target. Do not edit.",
			"",
			"import 'test_host.dart' as test_host;"
		];
		for(entry in entries) {
			chunks.push("");
			chunks.push(equalsDecl(types, entry));
			chunks.push("");
			chunks.push(formatDecl(types, entry));
			chunks.push("");
			chunks.push(assertDecl(types, entry));
		}
		return chunks.join("\n") + "\n";
	}

	/**
		Walks one registered type recording the module of every named
		declaration it references, mirroring the registry's own descent
		without `Context.follow` so named records keep their identity.
	**/
	static function registerTypeModules(imports: DartImports, t: Type, seen: Map<String, Bool>): Void {
		// Recursive declarations (an enum payload or record field naming
		// an enclosing type) terminate on the visited set; the walk only
		// collects import lines, so revisiting adds nothing.
		final key = Std.string(t);
		if(seen.exists(key)) {
			return;
		}
		seen.set(key, true);
		switch(t) {
			case TAbstract(a, params):
				final n = a.get().name;
				if(n == "Null" || n == "ReadOnlyArray") {
					registerTypeModules(imports, params[0], seen);
				}
			case TInst(c, params):
				if(c.get().name == "Array") {
					registerTypeModules(imports, params[0], seen);
				}
			case TType(d, _):
				final def = d.get();
				imports.type(def.module, def.name);
				registerStructModules(imports, def, seen);
			case TAnonymous(anon):
				final def = DartDecl.structTypedefs.get(DartDecl.structureSignature(anon));
				if(def != null) {
					registerTypeModules(imports, TType(def, []), seen);
				}
			case TEnum(e, _):
				final en = e.get();
				imports.type(en.module, en.name);
				for(name => construct in en.constructs) {
					switch(construct.type) {
						case TFun(args, _):
							for(arg in args) {
								registerTypeModules(imports, arg.t, seen);
							}
						case _: registerTypeModules(imports, construct.type, seen);
					}
				}
			case TLazy(f):
				registerTypeModules(imports, f(), seen);
			case _:
		}
	}

	static function registerStructModules(imports: DartImports, def: DefType, seen: Map<String, Bool>): Void {
		final key = "def:" + def.module + "." + def.name;
		if(seen.exists(key)) {
			return;
		}
		seen.set(key, true);
		switch(def.type) {
			case TAnonymous(an):
				for(f in an.get().fields) {
					registerTypeModules(imports, f.type, seen);
				}
			case TType(inner, _):
				registerStructModules(imports, inner.get(), seen);
			case _:
		}
	}

	// ------------------------------------------------------------------
	// Assertions
	// ------------------------------------------------------------------

	/**
		The generated assertion of one registered type: a mismatch raises
		the host failure with both canonical texts. The message composes
		through the resident formatter, which lives at the top of the
		test host library under its class name.
	**/
	static function assertDecl(types: DartType, entry: {tag: String, type: Type}): String {
		final t = types.of(nominalTypeOf(entry.type));
		return [
			"void assertEquals" + entry.tag + "(" + t + " expected, " + t + " actual, String message) {",
			"  if (!equals" + entry.tag + "(expected, actual)) {",
			"    throw test_host.TestFailure(test_host.TestCore.formatCanonicalMessage(test_host.currentTestId(), message, format" + entry.tag + "(expected), format" + entry.tag + "(actual), true));",
			"  }",
			"}"
		].join("\n");
	}

	// ------------------------------------------------------------------
	// Deep equality
	// ------------------------------------------------------------------

	/**
		The deep equality of one registered type: scalars and named
		records and variants compare through the native operator (their
		classes generate it), optionals pair nulls before descending,
		and lists compare element-wise through the element equality.
	**/
	static function equalsDecl(types: DartType, entry: {tag: String, type: Type}): String {
		final t = types.of(nominalTypeOf(entry.type));
		return switch(entry.type) {
			case TAbstract(a, params):
				switch(a.get().name) {
					case "Null":
						final inner = tagOfParam(params[0]);
						[
							"bool equals" + entry.tag + "(" + t + " a, " + t + " b) {",
							"  if (a == null || b == null) {",
							"    return a == null && b == null;",
							"  }",
							"  return equals" + inner + "(a, b);",
							"}"
						].join("\n");
					// The read-only view compares as the list it wraps.
					case "ReadOnlyArray":
						listEquals(entry.tag, t, params[0]);
					case _:
						"bool equals" + entry.tag + "(" + t + " a, " + t + " b) => a == b;";
				}
			case TInst(c, params):
				switch(c.get().name) {
					case "Array":
						listEquals(entry.tag, t, params[0]);
					case "Bytes":
						listEquals(entry.tag, t, null);
					case _:
						"bool equals" + entry.tag + "(" + t + " a, " + t + " b) => a == b;";
				}
			case _:
				"bool equals" + entry.tag + "(" + t + " a, " + t + " b) => a == b;";
		}
	}

	/**
		Element-wise list equality through the element's own generated
		equality; the native operator on lists compares references.
	**/
	static function listEquals(tag: String, t: String, elem: Null<Type>): String {
		final inner = tagOfParam(elem);
		return [
			"bool equals" + tag + "(" + t + " a, " + t + " b) {",
			"  if (a.length != b.length) {",
			"    return false;",
			"  }",
			"  for (var i = 0; i < a.length; i++) {",
			"    if (!equals" + inner + "(a[i], b[i])) {",
			"      return false;",
			"    }",
			"  }",
			"  return true;",
			"}"
		].join("\n");
	}

	static function tagOfParam(t: Null<Type>): String {
		if(t == null) {
			return "Int";
		}
		return DartTestTypes.tagOf(t);
	}

	// ------------------------------------------------------------------
	// Canonical formatting
	// ------------------------------------------------------------------

	static function formatDecl(types: DartType, entry: {tag: String, type: Type}): String {
		final name = "format" + entry.tag;
		final type = nominalTypeOf(entry.type);
		final t = types.of(type);
		return switch(type) {
			case TAbstract(a, params):
				switch(a.get().name) {
					case "Int": scalarWrapper(name, t, "test_host.TestCore.formatInt(v)");
					case "Float": scalarWrapper(name, t, "test_host.TestCore.formatFloat(v)");
					case "Bool": scalarWrapper(name, t, "test_host.TestCore.formatBool(v)");
					case "Null": optionalWrapper(name, t, params[0]);
					// The read-only view renders as the array it wraps.
					case "ReadOnlyArray": arrayWrapper(name, t, params[0]);
					case _: fail(entry.type);
				}
			case TInst(c, params):
				switch(c.get().name) {
					case "String": scalarWrapper(name, t, "test_host.TestCore.formatString(v)");
					case "Bytes": scalarWrapper(name, t, "test_host.TestCore.formatBytes(v)");
					case "Array": arrayWrapper(name, t, params[0]);
					case _: fail(entry.type);
				}
			case TType(def, _): structWrapper(name, t, structFieldsOf(def.get()));
			case TEnum(e, _): enumWrapper(name, t, e.get());
			case TLazy(f): formatDecl(types, {tag: entry.tag, type: f()});
			case _: fail(entry.type);
		}
	}

	static function scalarWrapper(name: String, t: String, body: String): String {
		return "String " + name + "(" + t + " v) => " + body + ";";
	}

	/** A missing optional renders as the bare canonical null. */
	static function optionalWrapper(name: String, t: String, inner: Type): String {
		return [
			"String " + name + "(" + t + " v) {",
			"  if (v == null) {",
			"    return 'null';",
			"  }",
			"  return format" + DartTestTypes.tagOf(inner) + "(v);",
			"}"
		].join("\n");
	}

	static function arrayWrapper(name: String, t: String, elem: Type): String {
		return [
			"String " + name + "(" + t + " v) {",
			"  final parts = <String>[];",
			"  for (var i = 0; i < v.length; i++) {",
			"    parts.add(format" + DartTestTypes.tagOf(elem) + "(v[i]));",
			"  }",
			"  return '[' + parts.join(', ') + ']';",
			"}"
		].join("\n");
	}

	/** A record renders its fields in declaration order, comma-space separated. */
	static function structWrapper(name: String, t: String, fields: Array<ClassField>): String {
		final parts = new Array<String>();
		for(i in 0...fields.length) {
			final f = fields[i];
			final head = (i == 0 ? "{" : ", ") + f.name + ": ";
			parts.push("'" + head + "' + format" + DartTestTypes.tagOf(f.type) + "(v." + f.name + ")");
		}
		return "String " + name + "(" + t + " v) => " + parts.join(" + ") + " + '}';";
	}

	/**
		A variant renders under its original construct name: bare for no
		payload, `Name(p1, p2)` with the payloads in declaration order.
		The switch exhausts over the sealed hierarchy.
	**/
	static function enumWrapper(name: String, t: String, en: EnumType): String {
		final constructs = [for(c in en.constructs) c];
		constructs.sort((a, b) -> Reflect.compare(a.index, b.index));
		final prefix = importPrefixOfEnum(en);
		final lines: Array<String> = [
			"String " + name + "(" + t + " v) {",
			"  switch (v) {"
		];
		for(ef in constructs) {
			final payloadArgs = switch(ef.type) {
				case TFun(args, _): args;
				case _: [];
			};
			final cls = DartDecl.constructClassName(en.name, ef.name);
			if(payloadArgs.length == 0) {
				lines.push("    case " + prefix + cls + "():");
				lines.push("      return '" + ef.name + "';");
				continue;
			}
			final bindings = [for(i in 0...payloadArgs.length) payloadArgs[i].name + ": var " + payloadArgName(payloadArgs[i], i)].join(", ");
			lines.push("    case " + prefix + cls + "(" + bindings + "):");
			final parts: Array<String> = [];
			for(i in 0...payloadArgs.length) {
				final arg = payloadArgs[i];
				final rendered = "format" + DartTestTypes.tagOf(arg.t) + "(" + payloadArgName(arg, i) + ")";
				parts.push(i == 0 ? "'" + ef.name + "(' + " + rendered : " + ', ' + " + rendered);
			}
			lines.push("      return " + parts.join(" ") + " + ')';");
		}
		lines.push("  }");
		lines.push("}");
		return lines.join("\n");
	}

	// ------------------------------------------------------------------
	// Internals
	// ------------------------------------------------------------------

	/** The import prefix of an enum's library, dot included. */
	static function importPrefixOfEnum(en: EnumType): String {
		final prefix = DartImports.importPrefixOf(en.module);
		return prefix.length > 0 ? prefix + "." : "";
	}

	static function payloadArgName(arg: {name: String}, index: Int): String {
		return arg.name != null && arg.name.length > 0 ? arg.name : "v" + index;
	}

	/**
		An anonymous record (a literal's own type) resolves its nominal
		declaration through the shape registry; `Context.follow` would
		unwrap the named spelling to the same shape and lose the name.
	**/
	static function nominalTypeOf(type: Type): Type {
		return switch(type) {
			case TAnonymous(anon):
				final def = DartDecl.structTypedefs.get(DartDecl.structureSignature(anon));
				if(def == null) {
					fail(type);
				}
				TType(def, []);
			case TLazy(f): nominalTypeOf(f());
			case _: type;
		};
	}

	/** The record fields of a typedef, alias chains followed, in declaration order. */
	static function structFieldsOf(def: DefType): Array<ClassField> {
		return switch(def.type) {
			case TAnonymous(anon):
				final fields = anon.get().fields.copy();
				fields.sort((a, b) -> Reflect.compare(Context.getPosInfos(a.pos).min, Context.getPosInfos(b.pos).min));
				fields;
			case TType(inner, _): structFieldsOf(inner.get());
			case _:
				Context.error("test assertion record type must be a structure typedef", def.pos);
				[];
		}
	}

	/** Mechanical escaping of generated-string content; operates on the actual characters. */
	static function escapeDartString(s: String): String {
		final b = new StringBuf();
		for(i in 0...s.length) {
			switch(s.charCodeAt(i)) {
				case 39: b.add("\\'");
				case 92: b.add("\\\\");
				case 10: b.add("\\n");
				case 13: b.add("\\r");
				case 9: b.add("\\t");
				case c: b.addChar(c);
			}
		}
		return b.toString();
	}

	static function fail(t: Type): String {
		Context.error("test assertion type has no Dart formatting in the subset: " + Std.string(t), Context.currentPos());
		return "";
	}
}
#end
