package tscompiler;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Type;
import reflaxe.BaseCompiler.BaseCompilerFileOutputType;
import reflaxe.PluginCompiler;
import reflaxe.ReflectCompiler;
import reflaxe.data.ClassFuncData;
import reflaxe.data.ClassVarData;
import reflaxe.data.EnumOptionData;

/**
	reflaxe plugin producing the TypeScript lane of the translatable
	subset (docs/specs/targets/07-reflaxe-typescript-target.md).

	Output layout is one file per Haxe module at the module's own path,
	plus a `runtime.ts` under the runtime-emit directory when runtime
	symbols are referenced, all written through the framework's output
	manager so `-D ts-output=<dir>` controls placement. Runtime files
	and runtime imports follow RuntimeConfig.
**/
class Compiler extends PluginCompiler<Compiler> {
	/** Module-base name to declaration parts, in arrival order. */
	final parts: Map<String, Array<String>> = [];

	/** Module-base name to emission context (imports per file). */
	final contexts: Map<String, TsDecl> = [];

	var current: Null<TsDecl> = null;

	public static function use() {
		ReflectCompiler.AddCompiler(new Compiler(), {
			fileOutputType: BaseCompilerFileOutputType.Manual,
			fileOutputExtension: ".ts",
			outputDirDefineName: "ts-output",
			unwrapTypedefs: false,
			normalizeEIE: false,
			preventRepeatVars: false,
			ignoreExterns: true,
		});
	}

	public function new() {
		super();
	}

	// ------------------------------------------------------------------
	// Declarations
	// ------------------------------------------------------------------

	public function compileClassImpl(classType: ClassType, varFields: Array<ClassVarData>, funcFields: Array<ClassFuncData>): Null<String> {
		if(!inSourceScope(classType.pos) || isSyntheticImpl(classType.name)) {
			return null;
		}
		final decl = contextFor(classType.module);
		final result = decl.classDecl(classType, varFields, funcFields);
		parts.get(classType.module).push(result);
		return result;
	}

	public function compileEnumImpl(enumType: EnumType, options: Array<EnumOptionData>): Null<String> {
		if(!inSourceScope(enumType.pos)) {
			return null;
		}
		final decl = contextFor(enumType.module);
		final result = decl.enumDecl(enumType, options);
		parts.get(enumType.module).push(result);
		return result;
	}

	public override function compileTypedef(def: DefType): Null<String> {
		if(!inSourceScope(def.pos)) {
			return null;
		}
		switch(def.type) {
			case TAnonymous(_):
			case _:
				return null;
		}
		final decl = contextFor(def.module);
		final result = decl.typedefDecl(def);
		parts.get(def.module).push(result);
		return result;
	}

	/**
		Entry point for expressions the framework itself needs lowered
		(field initializers and the like). Everything flows through the
		same typed-AST translator as class bodies.
	**/
	public function compileExpressionImpl(e: TypedExpr, topLevel: Bool): Null<String> {
		final decl = current != null ? current : new TsDecl("eval");
		return topLevel ? decl.topLevelStatements(e) : decl.rawExpression(e);
	}

	// ------------------------------------------------------------------
	// Output
	// ------------------------------------------------------------------

	public override function generateFilesManually() {
		final modules = [];
		for(module in parts.keys()) modules.push(module);
		modules.sort(Reflect.compare);
		for(module in modules) {
			final decl = contexts.get(module);
			final imports = decl.renderImports();
			final body = parts.get(module).join("\n\n");
			final content = '// Generated by the reflaxe TypeScript target. Do not edit.\n\n'
				+ imports
				+ (imports.length > 0 ? "\n" : "")
				+ body
				+ "\n";
			output.saveFile(modulePath(module), content);
		}
		final emitDir = RuntimeConfig.emitDir();
		if(emitDir != null && anyRuntimeUsed()) {
			output.saveFile(RuntimeConfig.emitPath(emitDir, "runtime.ts"), StringTools.trim(TsRuntime.SOURCE) + "\n");
		}
	}

	function anyRuntimeUsed(): Bool {
		for(decl in contexts.iterator()) {
			if(decl.usesRuntime()) {
				return true;
			}
		}
		return false;
	}

	// ------------------------------------------------------------------
	// Internals
	// ------------------------------------------------------------------

	function contextFor(module: String): TsDecl {
		current = contexts.exists(module) ? contexts.get(module) : null;
		if(current == null) {
			current = new TsDecl(module);
			contexts.set(module, current);
			parts.set(module, []);
		}
		return current;
	}

	/**
		The compilation scope is the intercepted source roots: a
		declaration lowers when its position file lies under one of them,
		whatever its package. The output path mirrors the module path:
		`pack.Module` lands at `pack/Module.ts`.
	**/
	function inSourceScope(pos: haxe.macro.Expr.Position): Bool {
		final file = Context.getPosInfos(pos).file;
		for(root in Intercept.sourceRoots()) {
			final prefix = root.charAt(root.length - 1) == "/" ? root : root + "/";
			if(StringTools.startsWith(file, prefix)
				|| StringTools.startsWith(file, "./" + prefix)
				|| file.indexOf("/" + prefix) >= 0) {
				return true;
			}
		}
		return false;
	}

	/** Haxe names synthesized abstract implementation classes `<Name>_Impl_`; they erase with the abstract. */
	function isSyntheticImpl(name: String): Bool {
		return StringTools.endsWith(name, "_Impl_");
	}

	function modulePath(module: String): String {
		return module.split(".").join("/") + ".ts";
	}
}
#end
