// Generated by the reflaxe TypeScript target. Do not edit.

import { console } from "./../std/Console.ts";

type HostFsModuleIsDirectory = { statSync: HostFsFnIsDirectory }; type HostFsFnIsDirectory = (p: string) => HostFsStatIsDirectory;; type HostModuleLoaderIsDirectory = (id: string) => unknown; type HostFsStatIsDirectory = { isDirectory: HostFsFnIsDirectoryStat }; type HostFsFnIsDirectoryStat = () => boolean; const fsIsDirectory = (p: string): boolean => { const host = globalThis as Record<string, unknown>; const probe = (host["process"] as Record<string, unknown> | undefined)?.getBuiltinModule as HostModuleLoaderIsDirectory | undefined; const fs = probe !== undefined ? probe("node:fs") as HostFsModuleIsDirectory : null; if (fs === null) { throw new Error("std.Fs is not available on this host"); } return fs.statSync(p).isDirectory(); };
type HostFsModuleReadText = { readFileSync: HostFsFnReadText }; type HostFsFnReadText = (p: string, options: string) => string;; type HostModuleLoaderReadText = (id: string) => unknown; const fsReadText = (p: string): string => { const host = globalThis as Record<string, unknown>; const probe = (host["process"] as Record<string, unknown> | undefined)?.getBuiltinModule as HostModuleLoaderReadText | undefined; const fs = probe !== undefined ? probe("node:fs") as HostFsModuleReadText : null; if (fs === null) { throw new Error("std.Fs is not available on this host"); } return fs.readFileSync(p, "utf8") as string; };

export class FsProbe {
  public static missingRoot(): string {
    return "out/fs-missing/probe/definitely-missing";
  }

  public static say(label: string, text: string): void {
    console.log(label + "|" + text);
  }

  public static messageOf(error: FsProbeFault): string {
    return (error === null ? "<not-caught>" : (() => {
  const bound = error;
  return bound.message;
})());
  }

  public static run(): void {
    const missing = FsProbe.missingRoot() + "/no-such-file.txt";
    FsProbe.say("m0", "probe-start");
    const dir = fsIsDirectory(missing);
    FsProbe.say("m1", `isDirectory-returned|${dir}`);
    let caught = false;
    let name = "<not-caught>";
    let message = "<not-caught>";
    try {
      const text = fsReadText(missing);
      FsProbe.say("m2", `readText-returned|${text}`);
    } catch (error) {
      if (error instanceof FsProbeFault) {
        caught = true;
        name = "haxe.Exception";
        message = FsProbe.messageOf(error);
      } else {
        throw error;
      }
    }
    FsProbe.say("m3", `readText-catch-ran|${caught}`);
    FsProbe.say("m4", `caught-declared-class|${name}`);
    FsProbe.say("m5", `caught-message|${message}`);
    FsProbe.say("m6", "uncaught-region-start");
    const escaped = fsReadText(missing);
    FsProbe.say("m7", `uncaught-region-returned|${escaped}`);
  }
}

export class FsProbeFault extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FsProbeFault";
  }
}
