import { describe, expect, test } from "bun:test";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

/**
 * Feature spec 24: every target compiler writes the package manifest of
 * its generated tree, on by default with a one-define opt-out. The
 * TypeScript target is exercised end to end here: a temp generation with a
 * relative runtime import produces a package.json whose tree a consumer
 * program runs under bun without any repository assistance. The Swift,
 * Kotlin, and Rust manifests carry no runnable toolchain in this
 * repository (swiftc without swift build, no Gradle), so their bytes are
 * pinned; cargo exercises the Rust manifest through the workspace.
 */

const REPO_ROOT = path.resolve(import.meta.dir, "../..");

interface GenerationOptions {
  tsOutput: string;
  testOutput: string;
  runtimeImport?: string;
  packageShell?: string;
}

interface CompilerOutcome {
  exitCode: number;
  stderr: string;
}

/**
 * Rewrites examples/ts.hxml for one generation: output trees go to the
 * given directories, the runtime import and the shell define follow the
 * scenario. An undefined packageShell drops the repository's opt-out so
 * the default emission runs.
 */
function rewriteHxml(source: string, opts: GenerationOptions): string {
  let out = source
    .replace("-D ts-test-output=reference/ts/gen-tests", `-D ts-test-output=${opts.testOutput}`)
    .replace("-D ts-output=reference/ts/gen", `-D ts-output=${opts.tsOutput}`);
  if(opts.runtimeImport !== undefined) {
    // Rewrite whatever specifier the repository's hxml currently carries,
    // so the scenario pins its own runtime import instead of inheriting
    // the repository state of that line.
    out = out.replace(/^-D runtime-import=[^\s]+$/m, `-D runtime-import=${opts.runtimeImport}`);
  }
  if(opts.packageShell === undefined) {
    out = out.replace("-D package-shell=none\n", "");
  } else {
    out = out.replace("-D package-shell=none", `-D package-shell=${opts.packageShell}`);
  }
  return out;
}

/** Runs one rewritten generation and reports the compiler outcome. */
async function runHaxe(hxmlName: string, content: string): Promise<CompilerOutcome> {
  const hxmlPath = path.join(REPO_ROOT, "out", hxmlName);
  fs.mkdirSync(path.dirname(hxmlPath), { recursive: true });
  fs.writeFileSync(hxmlPath, content);
  const proc = Bun.spawn(["haxe", path.relative(REPO_ROOT, hxmlPath)], {
    cwd: REPO_ROOT,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [exitCode, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()]);
  return { exitCode, stderr };
}

function tempTree(label: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), `boring-shell-${label}-`));
}

const DEFAULT_PACKAGE_JSON = [
  "{",
  '  "name": "generated",',
  '  "version": "0.1.0",',
  '  "private": true,',
  '  "type": "module",',
  '  "exports": {',
  '    "./boring/*": "./boring/*.ts",',
  '    "./haxe/*": "./haxe/*.ts",',
  '    "./registry/*": "./registry/*.ts",',
  '    "./runtime": "./runtime.ts",',
  '    "./std/*": "./std/*.ts",',
  '    "./tests/*": "./tests/*.ts"',
  "  },",
  '  "devDependencies": {',
  '    "typescript": "^5.9.0"',
  "  }",
  "}",
  "",
].join("\n");

/**
 * The generated-side manifest of the minimal Swift
 * `package-shell=emit` fixture (tests/haxe/swift-package-shell-emit): the
 * bytes one std.Fs.appendText compilation writes beside its sources.
 * Unlike the repository-root Package.swift pinned below, this manifest
 * belongs to the emitted tree, and until now no assertion covered it
 * (the reference tree runs with package-shell=none). Feature spec 24
 * Ruling: the manifest declares no dependency and no platform floor, and
 * SystemPackage enters the calling source file only (stdlib/17
 * build-chain migration rule 2).
 */
const SWIFT_EMIT_MANIFEST = [
  "// Generated by the reflaxe Swift target. Do not edit.",
  "// swift-tools-version:5.9",
  "import PackageDescription",
  "",
  "let package = Package(",
  '    name: "generated",',
  "    targets: [",
  "        .target(",
  '            name: "generated",',
  '            path: ".",',
  "            sources: [",
  '                "Main",',
  '                "Runtime.swift",',
  '                "std",',
  "            ]",
  "        )",
  "    ]",
  ")",
  "",
].join("\n");

const SWIFT_EMIT_MANIFEST_SHA256 = "8efa9d40c84536692751d7d9bc5537313d134e362e307b6cc166d8df53486678";

const SWIFT_EMIT_HXML = "tests/haxe/swift-package-shell-emit/emit.hxml";

const IDENTITY_PACKAGE_JSON = [
  "{",
  '  "name": "boring-demo",',
  '  "version": "9.9.9",',
  '  "license": "Apache-2.0",',
  '  "private": true,',
  '  "type": "module",',
  '  "exports": {',
  '    "./boring/*": "./boring/*.ts",',
  '    "./haxe/*": "./haxe/*.ts",',
  '    "./registry/*": "./registry/*.ts",',
  '    "./runtime": "./runtime.ts",',
  '    "./std/*": "./std/*.ts",',
  '    "./tests/*": "./tests/*.ts"',
  "  },",
  '  "devDependencies": {',
  '    "typescript": "^5.9.0"',
  "  }",
  "}",
  "",
].join("\n");

describe("package shell emission", () => {
  // Every test here drives full haxe subprocess pipelines whose wall time
  // scales with machine load; the explicit timeouts raise only the harness
  // patience for those subprocesses, never the asserted behavior.
  test("default emission writes package.json and the tree runs standalone", async () => {
    const tree = tempTree("default");
    try {
      const hxml = rewriteHxml(fs.readFileSync(path.join(REPO_ROOT, "examples/ts.hxml"), "utf8"), {
        tsOutput: tree,
        testOutput: path.join(tree, "../boring-shell-default-tests"),
        runtimeImport: "./runtime",
      });
      const result = await runHaxe("package-shell-default.hxml", hxml);
      expect(result.stderr).toBe("");
      expect(result.exitCode).toBe(0);

      expect(fs.readFileSync(path.join(tree, "package.json"), "utf8")).toBe(DEFAULT_PACKAGE_JSON);
      // The runtime import resolves per file against the tree the
      // compilation wrote: a nested module walks up to the root entry.
      expect(fs.readFileSync(path.join(tree, "boring/Fp32.ts"), "utf8")).toContain('from "../runtime.ts"');

      fs.writeFileSync(path.join(tree, "consumer.ts"), [
        'import { Fp32 } from "./boring/Fp32.ts";',
        "const bits = Fp32.toBits(1.5);",
        'if(bits !== 0x3fc00000) { throw new Error("bad bits: " + bits); }',
        'if(Fp32.fromBits(0x3fc00000) !== 1.5) { throw new Error("bad value"); }',
        'console.log("consumer-ok");',
        "",
      ].join("\n"));
      const consumer = Bun.spawn(["bun", "consumer.ts"], { cwd: tree, stdout: "pipe", stderr: "pipe" });
      const [consumerCode, consumerOut, consumerErr] = await Promise.all([
        consumer.exited,
        new Response(consumer.stdout).text(),
        new Response(consumer.stderr).text(),
      ]);
      expect(consumerErr).toBe("");
      expect(consumerCode).toBe(0);
      expect(consumerOut.trim()).toBe("consumer-ok");

      // The exports map resolves the package by name: a symlinked
      // node_modules entry routes "generated/boring/Fp32" through the
      // directory wildcard to the emitted .ts file.
      fs.mkdirSync(path.join(tree, "node_modules"));
      fs.symlinkSync(tree, path.join(tree, "node_modules", "generated"));
      fs.writeFileSync(path.join(tree, "consumer-pkg.ts"), [
        'import { Fp32 } from "generated/boring/Fp32";',
        'import { doubleToI64 } from "generated/runtime";',
        'if(doubleToI64(1.5).low !== 0) { throw new Error("bad runtime export"); }',
        'console.log("consumer-pkg-ok");',
        "",
      ].join("\n"));
      const pkgConsumer = Bun.spawn(["bun", "consumer-pkg.ts"], { cwd: tree, stdout: "pipe", stderr: "pipe" });
      const [pkgCode, pkgOut, pkgErr] = await Promise.all([
        pkgConsumer.exited,
        new Response(pkgConsumer.stdout).text(),
        new Response(pkgConsumer.stderr).text(),
      ]);
      expect(pkgErr).toBe("");
      expect(pkgCode).toBe(0);
      expect(pkgOut.trim()).toBe("consumer-pkg-ok");
    } finally {
      fs.rmSync(tree, { recursive: true, force: true });
      fs.rmSync(path.join(tree, "../boring-shell-default-tests"), { recursive: true, force: true });
    }
  }, 120000);

  test("identity defines flow into the manifest", async () => {
    const tree = tempTree("identity");
    try {
      const base = rewriteHxml(fs.readFileSync(path.join(REPO_ROOT, "examples/ts.hxml"), "utf8"), {
        tsOutput: tree,
        testOutput: path.join(tree, "../boring-shell-identity-tests"),
        runtimeImport: "./runtime",
      });
      const hxml = base.replace(
        "-D runtime-emit=.",
        "-D runtime-emit=.\n-D package-name=boring-demo\n-D package-version=9.9.9\n-D package-license=Apache-2.0",
      );
      const result = await runHaxe("package-shell-identity.hxml", hxml);
      expect(result.stderr).toBe("");
      expect(result.exitCode).toBe(0);
      expect(fs.readFileSync(path.join(tree, "package.json"), "utf8")).toBe(IDENTITY_PACKAGE_JSON);
    } finally {
      fs.rmSync(tree, { recursive: true, force: true });
      fs.rmSync(path.join(tree, "../boring-shell-identity-tests"), { recursive: true, force: true });
    }
  }, 120000);

  test("package-shell=none writes source only", async () => {
    const tree = tempTree("off");
    try {
      const hxml = rewriteHxml(fs.readFileSync(path.join(REPO_ROOT, "examples/ts.hxml"), "utf8"), {
        tsOutput: tree,
        testOutput: path.join(tree, "../boring-shell-off-tests"),
        runtimeImport: "./runtime",
        packageShell: "none",
      });
      const result = await runHaxe("package-shell-off.hxml", hxml);
      expect(result.stderr).toBe("");
      expect(result.exitCode).toBe(0);
      expect(fs.existsSync(path.join(tree, "package.json"))).toBe(false);
      expect(fs.existsSync(path.join(tree, "boring/Fp32.ts"))).toBe(true);
    } finally {
      fs.rmSync(tree, { recursive: true, force: true });
      fs.rmSync(path.join(tree, "../boring-shell-off-tests"), { recursive: true, force: true });
    }
  }, 120000);

  test("an invalid package-shell value aborts the compile", async () => {
    const tree = tempTree("invalid");
    try {
      const hxml = rewriteHxml(fs.readFileSync(path.join(REPO_ROOT, "examples/ts.hxml"), "utf8"), {
        tsOutput: tree,
        testOutput: path.join(tree, "../boring-shell-invalid-tests"),
        runtimeImport: "./runtime",
        packageShell: "bogus",
      });
      const result = await runHaxe("package-shell-invalid.hxml", hxml);
      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toContain("package-shell accepts emit or none");
    } finally {
      fs.rmSync(tree, { recursive: true, force: true });
      fs.rmSync(path.join(tree, "../boring-shell-invalid-tests"), { recursive: true, force: true });
    }
  }, 120000);

  test("a by-name runtime import with an emitted manifest aborts the compile", async () => {
    const tree = tempTree("byname");
    try {
      // The scenario pins its own by-name runtime import and drops the
      // repository's opt-out, so it no longer depends on what specifier
      // examples/ts.hxml currently carries (feature spec 24, Ruling 5:
      // a by-name import names a package coordinate the emitted
      // manifest cannot declare, so the combination stops the compile).
      const hxml = rewriteHxml(fs.readFileSync(path.join(REPO_ROOT, "examples/ts.hxml"), "utf8"), {
        tsOutput: tree,
        testOutput: path.join(tree, "../boring-shell-byname-tests"),
        runtimeImport: "@boring/runtime",
      });
      const result = await runHaxe("package-shell-byname.hxml", hxml);
      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toContain("package shell requires a relative runtime import");
    } finally {
      fs.rmSync(tree, { recursive: true, force: true });
      fs.rmSync(path.join(tree, "../boring-shell-byname-tests"), { recursive: true, force: true });
    }
  }, 120000);

  test("the Swift, Kotlin, and Rust manifests of the reference trees are pinned", () => {
    // The Swift target opts out of the emitted manifest
    // (package-shell=none): its test chain is the repository-root
    // SwiftPM package of the stdlib/17 build-chain migration, and the
    // generated trees carry no manifest of their own.
    expect(fs.existsSync(path.join(REPO_ROOT, "reference/swift/gen/Package.swift"))).toBe(false);
    const swiftPackage = fs.readFileSync(path.join(REPO_ROOT, "Package.swift"), "utf8");
    expect(swiftPackage).toContain('// swift-tools-version:6.0');
    expect(swiftPackage).toContain('.package(url: "https://github.com/apple/swift-system", exact: "1.6.6")');
    expect(swiftPackage).toContain('name: "Codec"');
    expect(swiftPackage).toContain('name: "BoringSwiftTests"');
    expect(swiftPackage).toContain('name: "BoringSwiftTestsF32"');

    expect(fs.readFileSync(path.join(REPO_ROOT, "reference/kotlin/gen/build.gradle.kts"), "utf8")).toBe([
      "// Generated by the reflaxe Kotlin target. Do not edit.",
      "plugins {",
      '    kotlin("jvm") version "2.4.10"',
      "}",
      "",
      "repositories {",
      "    mavenCentral()",
      "}",
      "",
      "sourceSets {",
      "    main {",
      '        kotlin.srcDir(".")',
      "    }",
      "}",
      "",
    ].join("\n"));

    expect(fs.readFileSync(path.join(REPO_ROOT, "reference/rust/gen/Cargo.toml"), "utf8")).toBe([
      "# Generated by the reflaxe Rust target. Do not edit.",
      "[package]",
      'name = "boring-codec-gen"',
      'version = "0.1.0"',
      'license = "MIT"',
      'edition = "2024"',
      "autotests = false",
      "",
      "[lints.clippy]",
      'as-conversions = "deny"',
      "",
      "[lib]",
      'path = "lib.rs"',
      "",
      "[[test]]",
      'name = "vector_gen"',
      'path = "../../../tests/rust/vector_gen.rs"',
      "",
    ].join("\n"));

    expect(fs.readFileSync(path.join(REPO_ROOT, "reference/rust-f32/gen/Cargo.toml"), "utf8")).toBe([
      "# Generated by the reflaxe Rust target. Do not edit.",
      "[package]",
      'name = "boring-codec-f32-gen"',
      'version = "0.1.0"',
      'license = "MIT"',
      'edition = "2024"',
      "autotests = false",
      "",
      "[lints.clippy]",
      'as-conversions = "deny"',
      "",
      "[lib]",
      'path = "lib.rs"',
      "",
      "[[test]]",
      'name = "vector_gen_f32"',
      'path = "../../../tests/rust/vector_gen_f32.rs"',
      "",
    ].join("\n"));
  });

  test("the generated Swift manifest of the minimal Fs.appendText fixture is pinned byte for byte", async () => {
    // BORING_SWIFT_EMIT_TREE is a diagnostic hook no CI run sets: it
    // points this assertion at an already-generated tree, which is how
    // the byte-pinning proof runs the same assertion against a /tmp copy
    // with one flipped byte in Package.swift. With the variable unset
    // the scenario generates the tree from the tracked fixture as usual.
    const override = process.env.BORING_SWIFT_EMIT_TREE;
    const tree = override === undefined ? tempTree("swift-emit") : override;
    try {
      if(override === undefined) {
        const hxml = fs.readFileSync(path.join(REPO_ROOT, SWIFT_EMIT_HXML), "utf8")
          .replace("-D swift-output=out/swift-package-shell-emit", `-D swift-output=${tree}`);
        const result = await runHaxe("swift-package-shell-emit.hxml", hxml);
        expect(result.stderr).toBe("");
        expect(result.exitCode).toBe(0);
      }

      const manifest = fs.readFileSync(path.join(tree, "Package.swift"));
      expect(manifest.toString("utf8")).toBe(SWIFT_EMIT_MANIFEST);
      expect(crypto.createHash("sha256").update(manifest).digest("hex")).toBe(SWIFT_EMIT_MANIFEST_SHA256);

      // Feature spec 24 Ruling: the generated manifest carries no
      // dependency field and no platform requirement, and the
      // SystemPackage dependency is not declared anywhere in the
      // emitted tree; it enters the calling source file's import block
      // only (stdlib/17 build-chain migration rule 2).
      const text = manifest.toString("utf8");
      expect(text.includes("dependencies")).toBe(false);
      expect(text.includes("platforms")).toBe(false);
      expect(text.includes("SystemPackage")).toBe(false);
      expect(fs.readFileSync(path.join(tree, "Main.swift"), "utf8")).toContain("import SystemPackage");
    } finally {
      if(override === undefined) {
        fs.rmSync(tree, { recursive: true, force: true });
      }
    }
  }, 120000);
});
