#if canImport(FoundationEssentials)
import FoundationEssentials
#elseif canImport(Darwin)
import Foundation
#endif
#if canImport(Glibc)
import Glibc
#endif
#if canImport(Darwin)
import Darwin
#endif
#if canImport(CRT)
import CRT
#endif
#if canImport(WinSDK)
import WinSDK
#endif

// Generated by the reflaxe Swift target. Do not edit.

private func boringFsIsDirectory(_ path: String) -> Bool {
    #if canImport(FoundationEssentials) || canImport(Darwin)
    #if canImport(FoundationEssentials)
    var isDirectory = false
    return FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory) && isDirectory
    #else
    var isDirectory = ObjCBool(false)
    return FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory) && isDirectory.boolValue
    #endif
    #else
    return false
    #endif
}

private func boringFsReadText(_ path: String) throws -> String {
    #if canImport(FoundationEssentials) || canImport(Darwin)
    guard let data = FileManager.default.contents(atPath: path) else {
        throw BoringException(message: path + ": read failed")
    }
    return String(decoding: data, as: UTF8.self)
    #else
    throw BoringException(message: "std.Fs is not available on this host")
    #endif
}

public enum FsProbe {
    public static func missingRoot() -> String {
        return "out/fs-missing/probe/definitely-missing"
    }

    public static func say(_ label: String, _ text: String) -> Void {
        console.log(label + "|" + text)
    }

    public static func messageOf(_ error: FsProbeFault) -> String {
        return ({ () -> String in
    let bound = error
    return bound.message
})()
    }

    public static func run() throws -> Void {
        let missing = FsProbe.missingRoot() + "/no-such-file.txt"
        FsProbe.say("m0", "probe-start")
        let dir = boringFsIsDirectory(missing)
        FsProbe.say("m1", "isDirectory-returned|\(dir)")
        var caught = false
        var name = "<not-caught>"
        var message = "<not-caught>"
        do {
            let text = try boringFsReadText(missing)
            FsProbe.say("m2", "readText-returned|" + text)
        } catch let error as FsProbeFault {
            caught = true
            name = "haxe.Exception"
            message = FsProbe.messageOf(error)
        } catch {
            throw error
        }
        FsProbe.say("m3", "readText-catch-ran|\(caught)")
        FsProbe.say("m4", "caught-declared-class|" + name)
        FsProbe.say("m5", "caught-message|" + message)
        FsProbe.say("m6", "uncaught-region-start")
        let escaped = try boringFsReadText(missing)
        FsProbe.say("m7", "uncaught-region-returned|" + escaped)
    }
}

public class FsProbeFault: BoringException {
    public init(_ message: String) {
        super.init(message: message)
    }
}
