// Generated by the reflaxe Dart target. Do not edit.
import 'dart:typed_data';
/// carry the bit patterns as the signed halves the codec boundaries
/// read, recombined through a typed view at the float edge.
class Int64Halves {
  final int high;
  final int low;

  Int64Halves(this.high, this.low);
}

/// The bit pattern of a double as its two 32-bit halves (stdlib/05).
Int64Halves doubleToI64(double value) {
  final bytes = ByteData(8);
  bytes.setFloat64(0, value, Endian.little);
  return Int64Halves(bytes.getInt32(4, Endian.little), bytes.getInt32(0, Endian.little));
}

/// The double of two 32-bit halves (stdlib/05).
double i64ToDouble(int low, int high) {
  final bytes = ByteData(8);
  bytes.setInt32(0, low, Endian.little);
  bytes.setInt32(4, high, Endian.little);
  return bytes.getFloat64(0, Endian.little);
}

/// The bit pattern of a float as a signed 32-bit integer (stdlib/05).
int floatToI32(double value) {
  final bytes = ByteData(4);
  bytes.setFloat32(0, value, Endian.little);
  return bytes.getInt32(0, Endian.little);
}

/// The float from a signed 32-bit raw bit pattern (stdlib/05).
double i32ToFloat(int bits) {
  final bytes = ByteData(4);
  bytes.setInt32(0, bits, Endian.little);
  return bytes.getFloat32(0, Endian.little);
}

/// Base class of the exception classes features/06 lowers; the caught
/// side reads the display message through it.
class BoringException implements Exception {
  final String message;

  /// The chained previous exception (features/06 previous chaining).
  final BoringException? previous;

  BoringException(this.message, {this.previous});
}

/// UTF-16 code-unit ordering of two strings, the order stdlib/07 rules
/// for sorted keys. Native order on this lane already compares by code
/// units, so the helper only provides the tear-off shape the sorted
/// builders bind.
int compareUnitOrder(String a, String b) {
  return a.compareTo(b);
}

/// Canonical float spelling shared by generated business modules.
String formatFloat(double v) {
  if (v.isNaN) return 'NaN';
  if (v == double.infinity) return 'Infinity';
  if (v == double.negativeInfinity) return '-Infinity';
  if (v == 0.0) return '0';
  final a = v.abs();
  if (a >= 0.000001 && a < 1000000000000000000000.0) {
    var s = v.toStringAsFixed(6);
    while (s.contains('.') && s.endsWith('0')) s = s.substring(0, s.length - 1);
    if (s.endsWith('.')) s = s.substring(0, s.length - 1);
    return s;
  }
  var s = v.toString().replaceFirst('E', 'e');
  s = s.replaceFirst('.0e', 'e');
  return s;
}

/// starts there. The resident cursor walk (stdlib/03) reads code points
/// through this; the same helper lives privately in every library that
/// inlines the walk.
int _codePointAt(String s, int i) {
  final lead = s.codeUnitAt(i);
  if (lead >= 55296 && lead <= 56319 && i + 1 < s.length) {
    final tail = s.codeUnitAt(i + 1);
    if (tail >= 56320 && tail <= 57343) {
      return 65536 + ((lead - 55296) << 10) + (tail - 56320);
    }
  }
  return lead;
}
final class StringTools {
  static bool isSpace(String s, int pos) {
    if (s.length == 0 || pos < 0 || pos >= s.length) {
      return false;
    }
    final int? c = (() { final _s = s; final _i = pos; return _i >= 0 && _i < _s.length ? _s.codeUnitAt(_i) : null; })();
    return c! > 8 && c < 14 || c == 32;
  }

  static String ltrim(String s) {
    final l = s.length;
    var r = 0;
    while (r < l && StringTools.isSpace(s, r)) {
      r++;
    }
    return (r > 0 ? (() { final _s = s; final _pos = r; final _len = l - r; if (_len < 0) return ''; final _start = _pos < 0 ? (_s.length + _pos < 0 ? 0 : _s.length + _pos) : (_pos > _s.length ? _s.length : _pos); final _end = _start + _len > _s.length ? _s.length : _start + _len; return _s.substring(_start, _end); })() : s);
  }

  static String rtrim(String s) {
    final l = s.length;
    var r = 0;
    while (r < l && StringTools.isSpace(s, l - r - 1)) {
      r++;
    }
    return (r > 0 ? (() { final _s = s; final _pos = 0; final _len = l - r; if (_len < 0) return ''; final _start = _pos < 0 ? (_s.length + _pos < 0 ? 0 : _s.length + _pos) : (_pos > _s.length ? _s.length : _pos); final _end = _start + _len > _s.length ? _s.length : _start + _len; return _s.substring(_start, _end); })() : s);
  }

  static String lpad(String s, String c, int l) {
    if (c.length <= 0) {
      return s;
    }
    var buf_b = "";
    final remaining = l - s.length;
    while (buf_b.length < remaining) {
      buf_b = buf_b + c;
    }
    buf_b = buf_b + s;
    return buf_b;
  }

  static String rpad(String s, String c, int l) {
    if (c.length <= 0) {
      return s;
    }
    var buf_b = "";
    buf_b = buf_b + s;
    final remaining = l - s.length;
    while (buf_b.length < remaining) {
      buf_b = buf_b + c;
    }
    return buf_b;
  }

  static String replace(String s, String sub, String by) {
    return s.split(sub).join(by);
  }
}

final class UString {
  static int count(String s) {
    var total = 0;
    var cursor = 0;
    final stop = s.length;
    while (cursor < stop) {
      total += 1;
      cursor = (cursor + (_codePointAt(s, cursor) > 65535 ? 2 : 1));
    }
    return total;
  }

  static int? at(String s, int index) {
    if (index < 0) {
      return null;
    }
    var remaining = index;
    var cursor = 0;
    final stop = s.length;
    while (cursor < stop) {
      if (remaining == 0) {
        return _codePointAt(s, cursor);
      }
      remaining -= 1;
      cursor = (cursor + (_codePointAt(s, cursor) > 65535 ? 2 : 1));
    }
    return null;
  }

  static String slice(String s, int from, int to) {
    final total = UString.count(s);
    var start = (from < 0 ? 0 : from);
    if (start > total) {
      start = total;
    }
    var stop = (to > total ? total : to);
    if (stop < 0) {
      stop = 0;
    }
    if (start >= stop) {
      return "";
    }
    var ordinal = 0;
    var startCursor = 0;
    var cursor = 0;
    while (ordinal < stop) {
      if (ordinal == start) {
        startCursor = cursor;
      }
      cursor = (cursor + (_codePointAt(s, cursor) > 65535 ? 2 : 1));
      ordinal += 1;
    }
    return s.substring(startCursor, cursor);
  }

  static List<int> toCodePoints(String s) {
    final out = <int>[];
    var cursor = 0;
    final stop = s.length;
    while (cursor < stop) {
      out.add(_codePointAt(s, cursor));
      cursor = (cursor + (_codePointAt(s, cursor) > 65535 ? 2 : 1));
    }
    return out;
  }

  static String fromCodePoint(int code) {
    return ((code >= 0 && code <= 1114111 && !(code >= 55296 && code <= 57343)) ? String.fromCharCode(code) : String.fromCharCode(0));
  }

  static String fromCodePoints(List<int> codes) {
    var out = "";
    for (var index = 0; index < codes.length; index++) {
      out = out + ((codes[index] >= 0 && codes[index] <= 1114111 && !(codes[index] >= 55296 && codes[index] <= 57343)) ? String.fromCharCode(codes[index]) : String.fromCharCode(0));
    }
    return out;
  }
}

final class SortedTable {
  static int compareInts(int a, int b) {
    if (a < b) {
      return -1;
    }
    if (a > b) {
      return 1;
    }
    return 0;
  }

  static int compareStrings(String a, String b) {
    final endA = a.length;
    final endB = b.length;
    var indexA = 0;
    var indexB = 0;
    while (indexA < endA && indexB < endB) {
      final codeA = _codePointAt(a, indexA);
      final codeB = _codePointAt(b, indexB);
      if (codeA != codeB) {
        if (codeA >= 57344 && codeA < 65536 && codeB >= 65536) {
          return 1;
        }
        if (codeB >= 57344 && codeB < 65536 && codeA >= 65536) {
          return -1;
        }
        if (codeA < codeB) {
          return -1;
        }
        return 1;
      }
      indexA = (indexA + (_codePointAt(a, indexA) > 65535 ? 2 : 1));
      indexB = (indexB + (_codePointAt(b, indexB) > 65535 ? 2 : 1));
    }
    if (indexA < endA) {
      return 1;
    }
    if (indexB < endB) {
      return -1;
    }
    return 0;
  }

  static SortedMapTableBuilder<K, V> mapBuilder<K, V>(int Function(K, K) compare) {
    return SortedMapTableBuilder<K, V>(<K>[], <V>[], compare);
  }

  static SortedSetTableBuilder<K> setBuilder<K>(int Function(K, K) compare) {
    return SortedSetTableBuilder<K>(<K>[], compare);
  }
}

final class SortedMapTable<K, V> {
  late final List<K> _keys;

  late final List<V> _values;

  late final int Function(K, K) _compare;

  SortedMapTable(this._keys, this._values, this._compare) {
  }

  V? get(K key) {
    final index = this._locate(key);
    if (index < 0) {
      return null;
    }
    return this._values[index];
  }

  bool has(K key) {
    return this._locate(key) >= 0;
  }

  int size() {
    return this._keys.length;
  }

  K keyAt(int index) {
    return this._keys[index];
  }

  V valueAt(int index) {
    return this._values[index];
  }

  String toString() {
    var out = "{";
    var i = 0;
    while (i < this._keys.length) {
      if (i > 0) {
        out = out + ", ";
      }
      out = out + "${this._keys[i]}=${this._values[i]}";
      i += 1;
    }
    return out + "}";
  }

  int _locate(K key) {
    var low = 0;
    var high = this._keys.length;
    while (low < high) {
      final mid = low + high >> 1;
      final order = this._compare(this._keys[mid], key);
      if (order < 0) {
        low = mid + 1;
      } else if (order > 0) {
        high = mid;
      } else {
        return mid;
      }
    }
    return -1;
  }
}

final class SortedMapTableBuilder<K, V> {
  late final List<K> _keys;

  late final List<V> _values;

  late final int Function(K, K) _compare;

  SortedMapTableBuilder(this._keys, this._values, this._compare) {
  }

  void put(K key, V value) {
    this._keys.add(key);
    this._values.add(value);
  }

  V? get(K key) {
    var index = this._keys.length;
    while (index > 0) {
      index -= 1;
      if (this._compare(this._keys[index], key) == 0) {
        return this._values[index];
      }
    }
    return null;
  }

  SortedMapTable<K, V> build() {
    final total = this._keys.length;
    final order = <int>[];
    var i = 0;
    while (i < total) {
      order.add(i);
      i += 1;
    }
    i = 1;
    while (i < total) {
      final current = order[i];
      var j = i;
      var moved = true;
      while (j > 0 && moved) {
        if (this._compare(this._keys[order[j - 1]], this._keys[current]) > 0) {
          while (order.length <= j) { order.add(0); };
          order[j] = order[j - 1];
          j -= 1;
        } else {
          moved = false;
        }
      }
      while (order.length <= j) { order.add(0); };
      order[j] = current;
      i += 1;
    }
    final outKeys = <K>[];
    final outValues = <V>[];
    i = 0;
    while (i < total) {
      var run = i;
      while (run + 1 < total && this._compare(this._keys[order[run + 1]], this._keys[order[i]]) == 0) {
        run += 1;
      }
      outKeys.add(this._keys[order[run]]);
      outValues.add(this._values[order[run]]);
      i = run + 1;
    }
    return SortedMapTable<K, V>(outKeys, outValues, this._compare);
  }
}

final class SortedSetTable<K> {
  late final List<K> _keys;

  late final int Function(K, K) _compare;

  SortedSetTable(this._keys, this._compare) {
  }

  bool has(K key) {
    return this._locate(key) >= 0;
  }

  int size() {
    return this._keys.length;
  }

  K at(int index) {
    return this._keys[index];
  }

  String toString() {
    var out = "[";
    var i = 0;
    while (i < this._keys.length) {
      if (i > 0) {
        out = out + ", ";
      }
      out = "${out}${this._keys[i]}";
      i += 1;
    }
    return out + "]";
  }

  int _locate(K key) {
    var low = 0;
    var high = this._keys.length;
    while (low < high) {
      final mid = low + high >> 1;
      final order = this._compare(this._keys[mid], key);
      if (order < 0) {
        low = mid + 1;
      } else if (order > 0) {
        high = mid;
      } else {
        return mid;
      }
    }
    return -1;
  }
}

final class SortedSetTableBuilder<K> {
  late final List<K> _keys;

  late final int Function(K, K) _compare;

  SortedSetTableBuilder(this._keys, this._compare) {
  }

  void put(K key) {
    this._keys.add(key);
  }

  SortedSetTable<K> build() {
    final total = this._keys.length;
    final order = <int>[];
    var i = 0;
    while (i < total) {
      order.add(i);
      i += 1;
    }
    i = 1;
    while (i < total) {
      final current = order[i];
      var j = i;
      var moved = true;
      while (j > 0 && moved) {
        if (this._compare(this._keys[order[j - 1]], this._keys[current]) > 0) {
          while (order.length <= j) { order.add(0); };
          order[j] = order[j - 1];
          j -= 1;
        } else {
          moved = false;
        }
      }
      while (order.length <= j) { order.add(0); };
      order[j] = current;
      i += 1;
    }
    final outKeys = <K>[];
    i = 0;
    while (i < total) {
      var run = i;
      while (run + 1 < total && this._compare(this._keys[order[run + 1]], this._keys[order[i]]) == 0) {
        run += 1;
      }
      outKeys.add(this._keys[order[run]]);
      i = run + 1;
    }
    return SortedSetTable<K>(outKeys, this._compare);
  }
}
