@main
struct ReadOnlyBoundaryRuntimeTests {
    static func main() {
        print("alias=\(ReadOnlyBoundaryOps.aliasSlots())")
        print("effect=\(ReadOnlyBoundaryOps.effectfulAlias())")
        print("reference=\(ReadOnlyBoundaryOps.referenceElement())")
        print("nullable-elements=\(ReadOnlyBoundaryOps.nullableElements())")
        print("nullable-literal-elements=\(ReadOnlyBoundaryOps.nullableLiteralElements())")
        print("nullable-local-literal-elements=\(ReadOnlyBoundaryOps.localNullableLiteralElements())")
        print("present-optional=\(ReadOnlyBoundaryOps.presentOptional())")
        print("absent-optional=\(ReadOnlyBoundaryOps.absentOptional())")
        print("guarded-present=\(ReadOnlyBoundaryOps.guardedRequired(TiqianArray<Int32>([4])))")
        print("guarded-absent=\(ReadOnlyBoundaryOps.guardedRequired(nil))")
        print("guarded-field=\(ReadOnlyBoundaryOps.guardedField())")
        print("null-reassigned=\(ReadOnlyBoundaryOps.nullReassignedView())")
        print("cleared=\(ReadOnlyBoundaryOps.clearedView())")
        print("direct-call=\(ReadOnlyBoundaryOps.directCallBoundary())")
        print("constructor=\(ReadOnlyBoundaryOps.constructorBoundary())")
        print("field-assignment=\(ReadOnlyBoundaryOps.fieldAssignmentBoundary())")
        print("static-field=\(ReadOnlyBoundaryOps.staticFieldBoundary())")
        print("return=\(ReadOnlyBoundaryOps.returnBoundary())")
        print("enum=\(ReadOnlyBoundaryOps.enumBoundary())")
        print("branch-true=\(ReadOnlyBoundaryOps.branchBoundary(true))")
        print("branch-false=\(ReadOnlyBoundaryOps.branchBoundary(false))")
        print("coalesced-null=\(ReadOnlyBoundaryOps.coalescedBoundary(nil))")
        print("coalesced-present=\(ReadOnlyBoundaryOps.coalescedBoundary(TiqianArray<Int32>([9])))")
        print("default-omitted=\(ReadOnlyBoundaryOps.registeredDefaultOmittedCall())")
        print("default-null=\(ReadOnlyBoundaryOps.registeredDefaultNullCall())")
        print("default-present=\(ReadOnlyBoundaryOps.registeredDefaultPresentCall())")
        print("nullable-fallback-omitted=\(ReadOnlyBoundaryOps.nullableFallbackOmittedCall())")
        print("nullable-fallback-null=\(ReadOnlyBoundaryOps.nullableFallbackNullCall())")
        print("nullable-fallback-present=\(ReadOnlyBoundaryOps.nullableFallbackPresentCall())")
        print("guarded-nullable-fallback=\(ReadOnlyBoundaryOps.guardedNullableFallbackBoundary(TiqianArray([45])))")
        print("traverse-readonly=\(ReadOnlyBoundaryOps.traverseReadOnlyView(ReadOnlyArray<Int32>(TiqianArray<Int32>([3, 4, 5]))))")
    }
}
