package swiftcompiler;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Type;

/**
	Generates the two fixed entries of the generated test tree
	(features/19): the `@main` runner that registers every @:test
	function in id order, and the per-type assertion and formatting
	functions the type-guided Test.equals calls resolve to. The
	canonical text follows the format the TypeScript host defined:
	comma-space separators, `{field: value}` records, `Kind(p1, p2)`
	variants under their original construct names.
**/
class SwiftTestHelper {
	public static function testMainSource(entries: Array<{id: String, runnerName: String, call: String}>): String {
		final sorted = entries.copy();
		sorted.sort((a, b) -> Reflect.compare(a.id, b.id));
		final lines: Array<String> = [
			"// Generated by the reflaxe Swift target. Do not edit.",
			"",
			"@main",
			"enum TestMain {",
			"    static func main() {"
		];
		for(e in sorted) {
			lines.push('        Test.run("${escapeSwiftString(e.id)}", "${escapeSwiftString(e.runnerName)}", ${e.call})');
		}
		lines.push("    }");
		lines.push("}");
		return lines.join("\n") + "\n";
	}

	public static function testHelperSource(): String {
		final imports = new SwiftImports("TestHelper");
		final types = new SwiftType(imports);
		final entries = SwiftTestTypes.registered.copy();
		entries.sort((a, b) -> Reflect.compare(a.tag, b.tag));
		final chunks: Array<String> = [
			"// Generated by the reflaxe Swift target. Do not edit.",
			""
		];
		for(entry in entries) {
			chunks.push(assertDecl(types, entry));
			chunks.push("");
			chunks.push(formatDecl(types, entry));
			chunks.push("");
		}
		return chunks.join("\n") + "\n";
	}

	// ------------------------------------------------------------------
	// Assertions
	// ------------------------------------------------------------------

	/**
		The generated assertion of one registered type: equality is the
		native operator (the target's structures, variants, arrays, and
		optionals conform to Equatable), and a mismatch raises the host
		failure with both canonical texts.
	**/
	static function assertDecl(types: SwiftType, entry: {tag: String, type: Type}): String {
		final t = types.of(nominalTypeOf(entry.type));
		return [
			"func assertEquals" + entry.tag + "(_ expected: " + t + ", _ actual: " + t + ", _ message: [UInt16]) throws -> Void {",
			"    if expected != actual {",
			"        throw TestFailure(message: TestCore.formatCanonicalMessage(Test.currentTestIdState(), message, format" + entry.tag + "(expected), format" + entry.tag + "(actual), true))",
			"    }",
			"}"
		].join("\n");
	}

	// ------------------------------------------------------------------
	// Canonical formatting
	// ------------------------------------------------------------------

	static function formatDecl(types: SwiftType, entry: {tag: String, type: Type}): String {
		final name = "format" + entry.tag;
		final type = nominalTypeOf(entry.type);
		final t = types.of(type);
		return switch(type) {
			case TAbstract(a, params):
				switch(a.get().name) {
					case "Int": scalarWrapper(name, t, "TestCore.formatInt(v)");
					case "Float": scalarWrapper(name, t, "TestCore.formatFloat(v)");
					case "Bool": scalarWrapper(name, t, "TestCore.formatBool(v)");
					case "Null": optionalWrapper(name, t, params[0]);
					// The read-only view renders as the array it wraps.
					case "ReadOnlyArray": arrayWrapper(name, t, params[0]);
					case _: fail(entry.type);
				}
			case TInst(c, params):
				switch(c.get().name) {
					case "String": scalarWrapper(name, t, "TestCore.formatString(Array(v.utf16))");
					case "Bytes": scalarWrapper(name, t, "TestCore.formatBytes(v)");
					case "Array": arrayWrapper(name, t, params[0]);
					case _: fail(entry.type);
				}
			case TType(def, _): structWrapper(name, t, structFieldsOf(def.get()));
			case TEnum(e, _): enumWrapper(name, t, e.get());
			case TLazy(f): formatDecl(types, {tag: entry.tag, type: f()});
			case _: fail(entry.type);
		}
	}

	static function scalarWrapper(name: String, t: String, body: String): String {
		return [
			"func " + name + "(_ v: " + t + ") -> [UInt16] {",
			"    return " + body,
			"}"
		].join("\n");
	}

	/** A missing optional renders as the bare canonical null. */
	static function optionalWrapper(name: String, t: String, inner: Type): String {
		return [
			"func " + name + "(_ v: " + t + ") -> [UInt16] {",
			"    if let value = v {",
			"        return format" + SwiftTestTypes.tagOf(inner) + "(value)",
			"    }",
			"    return Array(\"null\".utf16)",
			"}"
		].join("\n");
	}

	static function arrayWrapper(name: String, t: String, elem: Type): String {
		final lines: Array<String> = [
			"func " + name + "(_ v: " + t + ") -> [UInt16] {",
			"    var out: [UInt16] = Array(\"[\".utf16)",
			"    for i in 0..<v.count {",
			"        if i > 0 {",
			"            out += Array(\", \".utf16)",
			"        }",
			"        out += format" + SwiftTestTypes.tagOf(elem) + "(v[i])",
			"    }",
			"    out += Array(\"]\".utf16)",
			"    return out",
			"}"
		];
		return lines.join("\n");
	}

	/** A record renders its fields in declaration order, comma-space separated. */
	static function structWrapper(name: String, t: String, fields: Array<ClassField>): String {
		final lines: Array<String> = [
			"func " + name + "(_ v: " + t + ") -> [UInt16] {",
			"    var out: [UInt16] = Array(\"{\".utf16)"
		];
		for(i in 0...fields.length) {
			final f = fields[i];
			final prefix = i == 0 ? f.name + ": " : ", " + f.name + ": ";
			lines.push("    out += Array(\"" + prefix + "\".utf16)");
			lines.push("    out += format" + SwiftTestTypes.tagOf(f.type) + "(v." + f.name + ")");
		}
		lines.push("    out += Array(\"}\".utf16)");
		lines.push("    return out");
		lines.push("}");
		return lines.join("\n");
	}

	/**
		A variant renders under its original construct name: bare for no
		payload, `Name(p1, p2)` with the payloads in declaration order.
	**/
	static function enumWrapper(name: String, t: String, en: EnumType): String {
		final constructs = [for(c in en.constructs) c];
		constructs.sort((a, b) -> Reflect.compare(a.index, b.index));
		final lines: Array<String> = [
			"func " + name + "(_ v: " + t + ") -> [UInt16] {",
			"    switch v {"
		];
		for(ef in constructs) {
			final payloadArgs = switch(ef.type) {
				case TFun(args, _): args;
				case _: [];
			};
			final label = SwiftDecl.lowerFirst(ef.name);
			if(payloadArgs.length == 0) {
				lines.push("    case ." + label + ":");
				lines.push("        return Array(\"" + ef.name + "\".utf16)");
				continue;
			}
			final bindings = [for(i in 0...payloadArgs.length) "let " + payloadArgName(payloadArgs[i], i)].join(", ");
			lines.push("    case ." + label + "(" + bindings + "):");
			lines.push("        var out: [UInt16] = Array(\"" + ef.name + "(\".utf16)");
			for(i in 0...payloadArgs.length) {
				final arg = payloadArgs[i];
				if(i > 0) {
					lines.push("        out += Array(\", \".utf16)");
				}
				lines.push("        out += format" + SwiftTestTypes.tagOf(arg.t) + "(" + payloadArgName(arg, i) + ")");
			}
			lines.push("        out += Array(\")\".utf16)");
			lines.push("        return out");
		}
		lines.push("    }");
		lines.push("}");
		return lines.join("\n");
	}

	static function payloadArgName(arg: {name: String}, index: Int): String {
		return arg.name != null && arg.name.length > 0 ? arg.name : "v" + index;
	}

	/**
		An anonymous record (a literal's own type) resolves its nominal
		declaration through the shape registry; `Context.follow` would
		unwraps the named spelling to the same shape and lose the name.
	**/
	static function nominalTypeOf(type: Type): Type {
		return switch(type) {
			case TAnonymous(anon):
				final def = SwiftDecl.structTypedefs.get(SwiftDecl.structureSignature(anon));
				if(def == null) {
					fail(type);
				}
				TType(def, []);
			case TLazy(f): nominalTypeOf(f());
			case _: type;
		};
	}

	// ------------------------------------------------------------------
	// Internals
	// ------------------------------------------------------------------

	/** The record fields of a typedef, alias chains followed, in declaration order. */
	static function structFieldsOf(def: DefType): Array<ClassField> {
		return switch(def.type) {
			case TAnonymous(anon):
				final fields = anon.get().fields.copy();
				fields.sort((a, b) -> Reflect.compare(Context.getPosInfos(a.pos).min, Context.getPosInfos(b.pos).min));
				fields;
			case TType(inner, _): structFieldsOf(inner.get());
			case _:
				Context.error("test assertion record type must be a structure typedef", def.pos);
				[];
		}
	}

	/** Mechanical escaping of generated-string content; operates on the actual characters. */
	static function escapeSwiftString(s: String): String {
		final b = new StringBuf();
		for(i in 0...s.length) {
			switch(s.charCodeAt(i)) {
				case 34: b.add('\\"');
				case 92: b.add('\\\\');
				case 10: b.add('\\n');
				case 13: b.add('\\r');
				case 9: b.add('\\t');
				case 11: b.add('\\u{000B}');
				case 12: b.add('\\u{000C}');
				case 1: b.add('\\u{0001}');
				case c: b.addChar(c);
			}
		}
		return b.toString();
	}

	static function fail(t: Type): String {
		Context.error("test assertion type has no Swift formatting in the subset: " + Std.string(t), Context.currentPos());
		return "";
	}
}
#end
