// Generated by the reflaxe Dart target. Do not edit.
import 'dart:io';
import '../../runtime.dart' as runtime;
String missingRoot() {
  return "out/fs-missing/probe/definitely-missing";
}

void say(String label, String text) {
  print(label + "|" + text);
}

String messageOf(FsProbeFault error) {
  return (error == null ? "<not-caught>" : (() {
  final bound = error;
  return bound.message;
})());
}

void run() {
  final missing = missingRoot() + "/no-such-file.txt";
  say("m0", "probe-start");
  final dir = FileSystemEntity.isDirectorySync(missing);
  say("m1", "isDirectory-returned|${dir}");
  var caught = false;
  var name = "<not-caught>";
  var message = "<not-caught>";
  try {
    final text = File(missing).readAsStringSync();
    say("m2", "readText-returned|" + text);
  } on FsProbeFault catch (error) {
    caught = true;
    name = "haxe.Exception";
    message = messageOf(error);
  }
  say("m3", "readText-catch-ran|${caught}");
  say("m4", "caught-declared-class|" + name);
  say("m5", "caught-message|" + message);
  say("m6", "uncaught-region-start");
  final escaped = File(missing).readAsStringSync();
  say("m7", "uncaught-region-returned|" + escaped);
}

class FsProbeFault extends runtime.BoringException {
  FsProbeFault(String message) : super(message) {
  }
}
